version: "3.8"

services:
  fastapi:
    image: 060795916912.dkr.ecr.us-east-1.amazonaws.com/churn-prediction:Korayem512 
    container_name: fastapi_app
    ports:
      - "443:8000"
    networks:
      - monitor_net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9091"
    networks:
      - monitor_net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3001"
    networks:
      - monitor_net

networks:
  monitor_net:
