name: CI - Test & Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  test-build:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1 
      ECR_REPO: churn-prediction
      TAG_SUFFIX: Korayem512
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest tests

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build Docker image locally
        run: |
          docker build -t churn-prediction:test-build .
